In [4]:
# Read A CSV file\

import pandas as pd

# Reading a CSV file into a dataframe

sales_data = pd.read_csv('C:\\Users\\Administrator\\Downloads\\employees.csv')
sales_data.head()

,employee_id,name,age,department,city,salary,years_experience,performance_score,joined_2020_or_later
0,1,Alice,23,Support,Chicago,76048,5.3,1.6,Yes
1,2,Bob,24,Finance,Miami,43905,2.3,NaN,Yes
2,3,Charlie,56,Finance,Seattle,94987,4.8,3.4,Yes
3,4,Diana,43,Support,Miami,76421,3.5,4.8,Yes
4,5,Ethan,28,Sales,Miami,87052,17.0,3.4,No

In [8]:
# Read an Excel

df = pd.read_excel('C:\\Users\\Administrator\\Downloads\\DUCAT Student Responses.xlsx', sheet_name = 'Form Responses 1')
df.head()

,Timestamp,Sudent Name,Enrollment No.,Branch,Year,Mobile Number,Email Id
0,2026-03-20 13:17:41.273,Ansh Pandita,127915625,CSE-AIML,1st Year,7838556149,anshpandita11@gmail.com
1,2026-03-20 13:18:06.694,Manvi Sharma,50927912724,CST,2nd Year,8273030056,manvi7106@gmail.com
2,2026-03-20 13:18:24.477,Aditya Gupta,2327902725,CSE,1st Year,9318360869,aditya.gupta18116@gmail.com
3,2026-03-20 13:18:37.978,Lakshita Chauhan,1227915624,CSE-AIML,2nd Year,9625160053,lakshitac0611@gmail.com
4,2026-03-20 13:18:40.523,Aashish Dagar,50827902724,CSE,2nd Year,9891654180,Nfsaashish@gmail.com