In [2]:
import pandas as pd

# Reading the Dataset
df = pd.read_csv("C:\\Users\Administrator\\Downloads\\employees.csv")

df.head()

,employee_id,name,age,department,city,salary,years_experience,performance_score,joined_2020_or_later
0,1,Alice,23,Support,Chicago,76048,5.3,1.6,Yes
1,2,Bob,24,Finance,Miami,43905,2.3,NaN,Yes
2,3,Charlie,56,Finance,Seattle,94987,4.8,3.4,Yes
3,4,Diana,43,Support,Miami,76421,3.5,4.8,Yes
4,5,Ethan,28,Sales,Miami,87052,17.0,3.4,No

Information about the data

In [3]:
# view the first few rows of the dataframe

print("First few rows of the Dataframe:")
print(df.head())

First few rows of the Dataframe:
   employee_id     name  age department     city  salary  years_experience  \
0            1    Alice   23    Support  Chicago   76048               5.3
1            2      Bob   24    Finance    Miami   43905               2.3
2            3  Charlie   56    Finance  Seattle   94987               4.8
3            4    Diana   43    Support    Miami   76421               3.5
4            5    Ethan   28      Sales    Miami   87052              17.0

   performance_score joined_2020_or_later
0                1.6                  Yes
1                NaN                  Yes
2                3.4                  Yes
3                4.8                  Yes
4                3.4                   No

In [4]:
# View last few Row of the DataFrame:

print("\nLast few rows of the DataFrame:")
df.tail()

Last few rows of the DataFrame:

,employee_id,name,age,department,city,salary,years_experience,performance_score,joined_2020_or_later
25,26,Zane,48,Engineering,Portland,64957,2.3,3.6,No
26,27,Aaron,25,HR,Portland,52899,1.7,3.9,Yes
27,28,Bella,56,Engineering,Seattle,98800,3.2,1.7,Yes
28,29,Carlos,57,Sales,Portland,52833,1.5,5.0,Yes
29,30,Deepa,48,Engineering,Austin,103653,9.9,4.5,Yes

In [5]:
# Data type

df.dtypes

employee_id               int64
name                     object
age                       int64
department               object
city                     object
salary                    int64
years_experience        float64
performance_score       float64
joined_2020_or_later     object
dtype: object

In [6]:
# get a concise summary of dataframe:

print("\nSummary of the Dataframe:")
df.info()

Summary of the Dataframe:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   employee_id           30 non-null     int64
 1   name                  30 non-null     object
 2   age                   30 non-null     int64
 3   department            30 non-null     object
 4   city                  30 non-null     object
 5   salary                30 non-null     int64
 6   years_experience      30 non-null     float64
 7   performance_score     26 non-null     float64
 8   joined_2020_or_later  30 non-null     object
dtypes: float64(2), int64(3), object(4)
memory usage: 2.2+ KB

In [7]:
# Get basic statistics of numerical Columns

print("\nBasic statistics of numerical Columns")
df.describe()

Basic statistics of numerical Columns

,employee_id,age,salary,years_experience,performance_score
count,30.000000,30.000000,30.000000,30.000000,26.000000
mean,15.500000,41.333333,78074.966667,8.160000,3.380769
std,8.803408,12.393918,23474.953513,5.930785,1.223117
min,1.000000,23.000000,43905.000000,1.500000,1.100000
25%,8.250000,29.000000,54115.500000,3.225000,2.350000
50%,15.500000,42.000000,76234.500000,5.950000,3.500000
75%,22.750000,52.500000,99271.750000,12.850000,4.450000
max,30.000000,60.000000,119840.000000,19.900000,5.000000

In [8]:
# Summary Statistics

df.describe(include = 'all')

,employee_id,name,age,department,city,salary,years_experience,performance_score,joined_2020_or_later
count,30.000000,30,30.000000,30,30,30.000000,30.000000,26.000000,30
unique,NaN,30,NaN,5,8,NaN,NaN,NaN,2
top,NaN,Alice,NaN,Sales,Miami,NaN,NaN,NaN,Yes
freq,NaN,1,NaN,8,7,NaN,NaN,NaN,19
mean,15.500000,NaN,41.333333,NaN,NaN,78074.966667,8.160000,3.380769,NaN
std,8.803408,NaN,12.393918,NaN,NaN,23474.953513,5.930785,1.223117,NaN
min,1.000000,NaN,23.000000,NaN,NaN,43905.000000,1.500000,1.100000,NaN
25%,8.250000,NaN,29.000000,NaN,NaN,54115.500000,3.225000,2.350000,NaN
50%,15.500000,NaN,42.000000,NaN,NaN,76234.500000,5.950000,3.500000,NaN
75%,22.750000,NaN,52.500000,NaN,NaN,99271.750000,12.850000,4.450000,NaN
max,30.000000,NaN,60.000000,NaN,NaN,119840.000000,19.900000,5.000000,NaN

In [9]:
# Check for Missing Value in each column

print('\nMissing Value in each column')
df.isnull().sum()

Missing Value in each column

employee_id             0
name                    0
age                     0
department              0
city                    0
salary                  0
years_experience        0
performance_score       4
joined_2020_or_later    0
dtype: int64

In [10]:
# Get Unique value for Categorial Column

print('\nUnique value for Categorial Column:')
print(df['department'].unique())

Unique value for Categorial Column:
['Support' 'Finance' 'Sales' 'Engineering' 'HR']

In [11]:
print('\nUnique value for Categorial Column:')
df['city'].unique()

Unique value for Categorial Column:

array(['Chicago', 'Miami', 'Seattle', 'Boston', 'Denver', 'Portland',
       'New York', 'Austin'], dtype=object)

In [12]:
# Get the count of Unique Values for Categorial columns

print("\nCount of Unique Values for Categorial columns:")
print(df['department'].value_counts())

Count of Unique Values for Categorial columns:
department
Sales          8
Finance        7
Engineering    7
Support        4
HR             4
Name: count, dtype: int64

In [13]:
print("\nCount of Unique Values for Categorial columns:")
print(df['city'].value_counts())

Count of Unique Values for Categorial columns:
city
Miami       7
Seattle     7
Portland    5
Chicago     3
Boston      2
Denver      2
New York    2
Austin      2
Name: count, dtype: int64

In [14]:
# Checking for duplicate row in a datafarme

print("\nDuplicate row in a datafarme:")
print(df.duplicated().sum())

Duplicate row in a datafarme:
0