In [6]:
import pandas as pd

# Reading the Dataset
df = pd.read_csv('C:\\Users\\Administrator\\Downloads\\inventory_data (1).csv')
df.head()

,product_id,product_name,category,supplier,unit_price,quantity_in_stock,reorder_level,warehouse,last_restocked,discontinued
0,41,Pliers,electronics,Bolt Bros,76.26,196.0,20.0,A,05/24/2024,NaN
1,34,WRENCH,Electronics,Bolt Bros,20.75,125.0,25.0,NaN,01/13/23,Yes
2,51,Screwdriver,hardware,Bolt Bros,47.6,377.0,25.0,NaN,18-01-2024,NaN
3,30,Screwdriver,Accessory,Bolt Bros,63.17,41.0,10.0,B,02/12/23,Yes
4,49,Hammer,Electronic,Acme Co.,52.5,154.0,20.0,B,29-09-2023,No

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         65 non-null     int64
 1   product_name       65 non-null     object
 2   category           65 non-null     object
 3   supplier           65 non-null     object
 4   unit_price         65 non-null     object
 5   quantity_in_stock  65 non-null     float64
 6   reorder_level      51 non-null     float64
 7   warehouse          45 non-null     object
 8   last_restocked     59 non-null     object
 9   discontinued       48 non-null     object
dtypes: float64(2), int64(1), object(7)
memory usage: 5.2+ KB

In [7]:
print('\nMissing value in each column:')
print(df.isnull().sum())

Missing value in each column:
product_id            0
product_name          0
category              0
supplier              0
unit_price            0
quantity_in_stock     4
reorder_level        14
warehouse            20
last_restocked        6
discontinued         17
dtype: int64

In [15]:
# Handle mising values
# Fill missing values in 'stock' with the median of column

df['quantity_in_stock'] = df['quantity_in_stock'].fillna(df['quantity_in_stock'].median())

In [11]:
print('\nMissing values in each column: ')
print(df.isnull().sum())

Missing values in each column:
product_id            0
product_name          0
category              0
supplier              0
unit_price            0
quantity_in_stock     0
reorder_level        14
warehouse            20
last_restocked        6
discontinued         17
dtype: int64

In [16]:
# Check for Duplicates 

print('\nDuplicate rows in the Dataframe: ')
print(df.duplicated().sum())

Duplicate rows in the Dataframe:
5

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         65 non-null     int64
 1   product_name       65 non-null     object
 2   category           65 non-null     object
 3   supplier           65 non-null     object
 4   unit_price         65 non-null     object
 5   quantity_in_stock  65 non-null     float64
 6   reorder_level      51 non-null     float64
 7   warehouse          45 non-null     object
 8   last_restocked     59 non-null     object
 9   discontinued       48 non-null     object
dtypes: float64(2), int64(1), object(7)
memory usage: 5.2+ KB

In [30]:
# Changing the Data type of the product_id column
df['product_id'] = df['product_id'].astype(float)

In [28]:
print(df['unit_price'].dtype)

object

In [29]:
print(df['unit_price'].unique()[:10])

['76.26' '20.75' '47.6' '63.17' '52.5' '4.5' '237.31' '151.36' '39.86'
 '$89.86']

In [33]:
# Ensure 'Stock' and 'Price' are Positive

df = df[df['quantity_in_stock'] >= 0]
df = df[df['reorder_level'] >= 0]

In [34]:
# view Cleaned DataFrame

print('\nCleaned DataFrame: ')
df

Cleaned DataFrame:

,product_id,product_name,category,supplier,unit_price,quantity_in_stock,reorder_level,warehouse,last_restocked,discontinued
0,41.0,Pliers,electronics,Bolt Bros,76.26,196.0,20.0,A,05/24/2024,NaN
1,34.0,WRENCH,Electronics,Bolt Bros,20.75,125.0,25.0,NaN,01/13/23,Yes
2,51.0,Screwdriver,hardware,Bolt Bros,47.6,377.0,25.0,NaN,18-01-2024,NaN
3,30.0,Screwdriver,Accessory,Bolt Bros,63.17,41.0,10.0,B,02/12/23,Yes
4,49.0,Hammer,Electronic,Acme Co.,52.5,154.0,20.0,B,29-09-2023,No
5,8.0,GIZMO 1,Hardware,Bolt Bros,4.5,88.0,10.0,B,14-01-2024,yes
7,60.0,Work Gloves,Accessories,Global Supply,151.36,335.0,10.0,NaN,26-09-2024,no
8,45.0,Drill Bit Set,Hardware,Bolt Bros,39.86,344.0,50.0,A,2023-02-10,yes
9,13.0,Thingamajig,Hardware,Global Supply,$89.86,9.0,50.0,C,11-09-2024,NaN
12,15.0,Gadget Y,hardware,ACME CO,109.33,39.0,50.0,D,03/28/2023,yes
13,17.0,Thingamajig,Electronics,Bolt Bros.,126.04,161.0,50.0,B,NaN,N
14,16.0,Widget A,HARDWARE,Global Supply,164.83,275.0,10.0,A,2024-10-27,yes
15,24.0,Widget B,hardware,Bolt Bros.,102.38,258.0,25.0,A,12/05/2024,NaN
16,54.0,Widget B,accessories,Global Supply,69.17,220.0,25.0,C,2024-09-01,Yes
17,56.0,Tape Measure,tools,Global Supply Inc,188.59,28.0,50.0,NaN,06/14/23,No
18,48.0,BOLT SET,hardware,Global Supply Inc,21.65,212.0,20.0,D,NaN,N
20,50.0,Level,safety,Acme Co,237.27,196.0,10.0,NaN,2023-02-23,yes
21,19.0,Gadget Y,Accessory,Global Supply,196.39,281.0,20.0,C,NaN,No
22,52.0,WIDGET A,TOOLS,Global Supply Inc,238.95,488.0,50.0,C,11/13/23,No
25,28.0,Screwdriver,hardware,Global Supply,245.5,2.0,25.0,D,03/28/23,Y
26,22.0,Gizmo 1,Tool,Global Supply,41.95,109.0,50.0,NaN,03/07/2024,N
27,37.0,Drill Bit Set,Electronics,Global Supply,224.58,7.0,50.0,NaN,11/06/2023,NaN
28,46.0,Widget B,HARDWARE,Bolt Bros.,132.77,386.0,10.0,C,08/19/2024,NaN
29,9.0,Drill Bit Set,Tool,Global Supply Inc,100.42,241.0,10.0,B,NaN,no
31,38.0,Screwdriver,electronics,Global Supply Inc,31.33,220.0,25.0,C,02/07/24,No
32,11.0,Gadget Y,safety,Global Supply,79.0,378.0,25.0,D,2023-06-15,no
33,6.0,Bolt Set,safety,Global Supply Inc,221.93,476.0,20.0,NaN,03/02/2023,Y
36,43.0,Thingamajig,Tool,Bolt Bros.,144.21,346.0,20.0,A,09/12/23,NaN
37,26.0,Doohickey,Electronics,ACME CO,51.64,151.0,20.0,C,11/19/2024,Y
38,7.0,Doohickey,Safety,ACME CO,113.12,447.0,50.0,NaN,01-03-2024,NaN
39,55.0,Gadget Y,safety,Global Supply Inc,203.98,249.0,25.0,NaN,09/13/2024,N
40,3.0,Gizmo 2,hardware,Acme Co.,137.61,25.0,50.0,NaN,11/18/23,NaN
42,36.0,Gadget X,safety,Global Supply Inc,53.64,102.0,10.0,B,26-09-2023,yes
43,32.0,Drill Bit Set,tools,Acme Co.,9.24,179.0,50.0,D,2024-10-04,no
44,22.0,Gizmo 1,Tool,Global Supply,41.95,109.0,50.0,NaN,03/07/2024,N
46,5.0,Level,TOOLS,Global Supply,174.28,291.0,10.0,A,2024-04-30,Yes
47,20.0,SAFETY GOGGLES,Tool,Global Supply,153.71,257.0,25.0,D,05/04/2024,Y
48,40.0,Wrench,Accessories,Acme Co.,13.79,225.0,20.0,NaN,2024-05-12,yes
49,12.0,Drill Bit Set,TOOLS,Acme Co.,174.5,182.0,25.0,B,29-05-2024,no
50,24.0,Widget B,hardware,Bolt Bros.,102.38,258.0,25.0,A,12/05/2024,NaN
52,3.0,Gizmo 2,hardware,Acme Co.,137.61,25.0,50.0,NaN,11/18/23,NaN
53,21.0,Thingamajig,Tool,Global Supply,80.02,214.0,25.0,A,08-06-2023,yes
54,57.0,Sprocket,safety,Global Supply,44.54,230.0,20.0,NaN,2024-11-11,Y
55,1.0,Gizmo 1,Accessories,Global Supply,146.32,220.0,50.0,D,NaN,No
56,53.0,Level,Safety,Global Supply,92.02,10.0,20.0,NaN,02/11/23,Yes
58,59.0,Doohickey,Safety,Acme Co.,2.62,113.0,25.0,A,2023-08-27,Yes
60,47.0,EXTENSION CORD,accessories,Global Supply,70.73,424.0,50.0,NaN,2023-09-10,NaN
61,39.0,Pliers,Electronics,Acme Co,208.92,474.0,25.0,D,14-07-2023,NaN
62,3.0,Gizmo 2,hardware,Acme Co.,137.61,25.0,50.0,NaN,11/18/23,NaN
63,33.0,Widget A,Accessory,Acme Co.,165.34,372.0,10.0,C,07/30/2023,NaN
64,27.0,Widget A,tools,Global Supply,62.55,332.0,50.0,NaN,07-02-2024,no